---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
    customize:
      cpus: 2
      memory: 1024

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[ktc-logging::server_logstash]
    - recipe[ktc-logging::server_es]
    - recipe[ktc-logging::client]

clusters:
  default:
    - default
